export const properties = [
    {
      id: 1,
      slug: "luxury-apartment-at-eskaton",
      title: "Luxury Apartment at Eskaton",
      type: "Apartment/Flats",
      purpose: "rent",
      price: 55000,
      priceType: "monthly",
      location: "Eskaton",
      city: "Dhaka",
      bedrooms: 3,
      bathrooms: 4,
      size: 2000,
      image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      owner: "Bipul Saha",
      ownerType: "Property owner",
      postedAt: "2026-05-23T07:00:53",
      featured: true,
      balconies: 2,
      furnishing: "Semi-furnished",
      garage: "1 Car Parking",
      floor: 8,
      availableFrom: "June 01, 2026",
      preferredTenant: "Family",
      deposit: 110000,
      features: ["Lift", "Generator", "Security", "CCTV"],
      address: "House 12, Road 5, Eskaton Garden, Dhaka",
      description: "A premium 2000 sqft apartment in the heart of Eskaton with breathtaking city views. Features a spacious living area, modern kitchen, and 3 well-appointed bedrooms. The building offers 24/7 security, lift access, and dedicated car parking.",
    },
    {
      id: 2,
      slug: "spacious-flat-at-mohammadpur",
      title: "Spacious Flat at Mohammadpur",
      type: "Apartment/Flats",
      purpose: "rent",
      price: 19999,
      priceType: "monthly",
      location: "Mohammadpur",
      city: "Dhaka",
      bedrooms: 4,
      bathrooms: 3,
      size: 1508,
      image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      owner: "Delwar Hossain",
      ownerType: "Property owner",
      postedAt: "2026-05-23T06:09:14",
      featured: false,
      balconies: 2,
      furnishing: "Unfurnished",
      garage: "1 Car Parking",
      floor: 6,
      availableFrom: "June 01, 2026",
      preferredTenant: "Family",
      deposit: 0,
      features: ["Lift"],
      address: "43/13-D, Shekhertek Road 06, Shymoly Housing Society, Mohammedpur, Dhaka",
      description: "Living room, Dining Room, Kitchen, 4 Bedrooms, 3 Toilets, 2 Balconies. Lift and Car Parking available.",
    },
    {
      id: 3,
      slug: "modern-apartment-at-uttara",
      title: "Modern Apartment at Uttara",
      type: "Apartment/Flats",
      purpose: "rent",
      price: 23000,
      priceType: "monthly",
      location: "Uttara",
      city: "Dhaka",
      bedrooms: 3,
      bathrooms: 3,
      size: 1400,
      image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
      owner: "Afrida Zarin Quader",
      ownerType: "Property owner",
      postedAt: "2026-05-23T06:06:56",
      featured: false,
      balconies: 1,
      furnishing: "Unfurnished",
      garage: null,
      floor: 4,
      availableFrom: "June 15, 2026",
      preferredTenant: "Family",
      deposit: 46000,
      features: ["Lift", "Generator"],
      address: "Sector 7, Uttara, Dhaka",
      description: "Bright and airy 1400 sqft apartment in Uttara with great connectivity. Perfect for families looking for a comfortable home in a peaceful neighbourhood.",
    },
    {
      id: 4,
      slug: "premium-flat-at-mohammadpur",
      title: "Premium Flat at Mohammadpur",
      type: "Apartment/Flats",
      purpose: "rent",
      price: 20000,
      priceType: "monthly",
      location: "Mohammadpur",
      city: "Dhaka",
      bedrooms: 4,
      bathrooms: 3,
      size: 1500,
      image: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
      owner: "M D DIDAR",
      ownerType: "Property owner",
      postedAt: "2026-05-23T06:05:06",
      featured: false,
      balconies: 2,
      furnishing: "Partially furnished",
      garage: null,
      floor: 5,
      availableFrom: "July 01, 2026",
      preferredTenant: "Family",
      deposit: 40000,
      features: ["Lift", "Security"],
      address: "Mohammadpur, Dhaka",
      description: "Well-maintained 1500 sqft apartment with 4 bedrooms. Located in a prime area of Mohammadpur with easy access to markets and transport.",
    },
    {
      id: 5,
      slug: "cozy-flat-at-malibag",
      title: "Cozy Flat at Malibag",
      type: "Apartment/Flats",
      purpose: "rent",
      price: 19000,
      priceType: "monthly",
      location: "Malibag",
      city: "Dhaka",
      bedrooms: 2,
      bathrooms: 2,
      size: 850,
      image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      owner: "Md. Sahariar Khan",
      ownerType: "Property owner",
      postedAt: "2026-05-23T01:24:42",
      featured: false,
      balconies: 1,
      furnishing: "Furnished",
      garage: null,
      floor: 3,
      availableFrom: "June 01, 2026",
      preferredTenant: "Bachelor/Family",
      deposit: 38000,
      features: ["Security"],
      address: "Malibag, Dhaka",
      description: "Compact and fully furnished 850 sqft apartment in Malibag. Ideal for small families or working couples. Very close to public transport.",
    },
    {
      id: 6,
      slug: "grand-flat-at-banasree",
      title: "Grand Flat at Banasree",
      type: "Apartment/Flats",
      purpose: "rent",
      price: 80000,
      priceType: "monthly",
      location: "Banasree",
      city: "Dhaka",
      bedrooms: 2,
      bathrooms: 3,
      size: 1795,
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
      owner: "Md Rabiul Hossain",
      ownerType: "Property owner",
      postedAt: "2026-05-22T23:05:49",
      featured: true,
      balconies: 3,
      furnishing: "Semi-furnished",
      garage: "2 Car Parking",
      floor: 10,
      availableFrom: "June 01, 2026",
      preferredTenant: "Family",
      deposit: 160000,
      features: ["Lift", "Generator", "Security", "CCTV", "Swimming Pool"],
      address: "Banasree, Block C, Dhaka",
      description: "Prestigious 1795 sqft apartment in the upscale Banasree area. Premium amenities include swimming pool, rooftop garden, and 24/7 concierge service.",
    },
    {
      id: 7,
      slug: "family-flat-at-mirpur-1",
      title: "Family Flat at Mirpur 1",
      type: "Apartment/Flats",
      purpose: "rent",
      price: 17000,
      priceType: "monthly",
      location: "Mirpur 1",
      city: "Dhaka",
      bedrooms: 3,
      bathrooms: 3,
      size: 1450,
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
      owner: "M.Shah Alam",
      ownerType: "Property owner",
      postedAt: "2026-05-22T19:26:08",
      featured: false,
      balconies: 2,
      furnishing: "Unfurnished",
      garage: null,
      floor: 4,
      availableFrom: "June 01, 2026",
      preferredTenant: "Family",
      deposit: 34000,
      features: ["Generator"],
      address: "Mirpur 1, Dhaka",
      description: "Spacious family apartment in Mirpur 1. Renovated kitchen and bathrooms, large living area, and two balconies with garden views.",
    },
    {
      id: 8,
      slug: "penthouse-at-gulshan-2",
      title: "Penthouse at Gulshan 2",
      type: "Apartment/Flats",
      purpose: "sale",
      price: 18500000,
      priceType: "total",
      location: "Gulshan 2",
      city: "Dhaka",
      bedrooms: 5,
      bathrooms: 5,
      size: 4200,
      image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      owner: "Rahim Properties",
      ownerType: "Company",
      postedAt: "2026-05-22T15:00:00",
      featured: true,
      balconies: 4,
      furnishing: "Fully furnished",
      garage: "3 Car Parking",
      floor: 18,
      availableFrom: "Immediate",
      preferredTenant: null,
      deposit: 0,
      features: ["Lift", "Generator", "Security", "CCTV", "Swimming Pool", "Gym"],
      address: "Gulshan 2, Dhaka 1212",
      description: "Exclusive penthouse in Gulshan 2 with panoramic city views. 4200 sqft of luxury living with high-end finishes, smart home features, and rooftop terrace.",
    },
  ];
  
  export const locations = ["All", "Eskaton", "Mohammadpur", "Uttara", "Malibag", "Banasree", "Mirpur 1", "Gulshan 2"];
  export const propertyTypes = ["All", "Apartment/Flats", "House", "Office", "Shop"];